:max_retries: 5
:concurrency: 10
staging:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS", 10).to_i %>
production:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS", 20).to_i %>
:queues:
  - collect
:schedule:
  disbursement_collect_job:
    cron: "0 1 * * 1 Europe/Madrid"
    class: DisbursementCollectJob
    queue: collect
    description: 'At 01:00 AM, only on Monday'  
